import java.util.ArrayList;

import acsse.csc2a.sim.AbstractFactory.ISensorFactory;
import acsse.csc2a.sim.AbstractProduct.ICoastalSensor;
import acsse.csc2a.sim.AbstractProduct.IDesertSensor;
import acsse.csc2a.sim.AbstractProduct.IMountainSensor;
import acsse.csc2a.sim.tester.TestPractical;
import acsse.csc2a.sim.util.ESensorType;
import acsse.csc2a.sim.util.SensorDeployer;

/* |------------------------------------------------|
*
* 				DO NOT EDIT THIS FILE!
* YOU NEED TO MAKE YOUR SOLUTION WORK WITH THIS MAIN
*
*   During marking we may replace this main with a 
*  different one to test the functionality of your
*                 Factory classes
* |------------------------------------------------|
*/

/**
 * Main class of program
 */
public class Main {

	public static void main(String[] args) {
		ArrayList<IMountainSensor> mountainSensors = new ArrayList<>();
		ArrayList<IDesertSensor> desertSensors = new ArrayList<>();
		ArrayList<ICoastalSensor> coastalSensors = new ArrayList<>();

		// Iterate over sensor types (PASSIVE and ACTIVE)
		for (ESensorType type : ESensorType.values()) {
			ISensorFactory factory = SensorDeployer.getFactory(type);
			mountainSensors.add(factory.createMountainSensor());
			desertSensors.add(factory.createDesertSensor());
			coastalSensors.add(factory.createCoastalSensor());
		}

		// Simulate Mountain Sensors
		for (IMountainSensor sensor : mountainSensors) {
			sensor.deploy();
		}

		// Simulate Desert Sensors
		for (IDesertSensor sensor : desertSensors) {
			sensor.deploy();
		}

		// Simulate Coastal Sensors
		for (ICoastalSensor sensor : coastalSensors) {
			sensor.deploy();
		}

		// Run practical test suite
		TestPractical.Test();
	}
}

/* |------------------------------------------------|
*
* 				DO NOT EDIT THIS FILE!
* YOU NEED TO MAKE YOUR SOLUTION WORK WITH THIS MAIN
*
*   During marking we may replace this main with a 
*  different one to test the functionality of your
*                 Factory classes
* |------------------------------------------------|
*/
